services:
  mock-data-generator:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ../../.env
    volumes:
      - .:/scripts
      - ../../:/workspace
      - ../../shared/python:/shared-python
    environment:
      - POSTGRES_HOST=spontaneousai-db-1
      - POSTGRES_PORT=5432
      - POSTGRES_ATTRACTIONS_DB=${POSTGRES_ATTRACTIONS_DB:-attractions}
      - POSTGRES_USERS_DB=${POSTGRES_USERS_DB:-users}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - PYTHONPATH=/scripts:/shared-python
    networks:
      - spontaneousai_default
    command: python /scripts/generate-mock-data.py

networks:
  spontaneousai_default:
    external: true

